version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      # - run:
      #     command: ./manage.py test
      #     name: Test

  # TODO
  # deploy-to-gcp:
  #   docker:
  #     - image: ubuntu
  #   steps:
  #     -

workflows:
  main:
    jobs:
      - build-and-test
      # - deploy-to-gcp
