version: 2.1

orbs:
  python: circleci/python@0.2.1
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      # - run:
      #     command: python -m pylint crawler_news/spiders/*
      #     name: lint
      - run:
          command: python -m scrapy check
          name: Test scrapy

  deploy-to-gcp:
    docker:
      - image: google/cloud-sdk
    steps:
      - run:
          command: |
            # echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            # gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            # gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet beta compute ssh --zone ${GOOGLE_COMPUTE_ZONE} "simple-deploy" --project ${GOOGLE_PROJECT_ID}
            pwd
            docker -v
            cat .ssh/authorized_keys
          name: Run gcloud

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - develop
                - /feature.*/
                - /circleci.*/
      - deploy-to-gcp:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - /circleci.*/
