version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      # - run:
      #     command: python -m pylint crawler_news/spiders/*
      #     name: lint
      - run:
          command: python -m scrapy check
          name: Test scrapy

  deploy-to-gcp:
    docker:
      - image: google/cloud-sdk
    steps:
      - add_ssh_keys:
          fingerprints:
            - "dc:03:4c:a5:1c:a6:52:ec:28:a6:9a:ad:86:d3:cc:10"
      - run:
          command: |
            pwd
            ls
            echo ${GCLOUD_SERVICE_KEY} | base64 -d | gcloud auth activate-service-account --key-file=-
            gcloud --quiet beta compute ssh --zone ${GOOGLE_COMPUTE_ZONE} "${GOOGLE_CE_NAME}" --project ${GOOGLE_PROJECT_ID}
            pwd
            docker -v
          name: Deploy on gcloud

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - develop
                - /feature.*/
                - /circleci.*/
      - deploy-to-gcp:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
                - /circleci.*/
