version: 2.1

orbs:
  python: circleci/python@0.2.1
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: scrapy check
          name: Test

  # TODO
  # deploy-to-gcp:
  #   docker:
  #     - image: ubuntu
  #   steps:
  #     -

workflows:
  main:
    jobs:
      - build-and-test
      # - deploy-to-gcp
