version: 2.1

orbs:
  python: circleci/python@0.2.1
  gcp-cli: circleci/gcp-cli@1.8.4

jobs:
  build-and-test:
    # executor: python/default
    docker:
      - image: python:3.7-stretch
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      # - run:
      #     command: python -m pylint crawler_news/spiders/*
      #     name: lint
      - run:
          command: python -m scrapy check
          name: Test scrapy

  # TODO
  # deploy-to-gcp:
  #   docker:
  #     - image: ubuntu
  #   steps:
  #     -

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - develop
                - /feature.*/
                - /circleci.*/
      # - deploy-to-gcp:
      #     requires:
      #       - build-and-test
      #     filters:
      #       branches:
      #         only: master
